### ISSUE TITLE
2.0.0-rc2 Blank page when open tasklists on 10.0.0

### ISSUE THREAD

**Issue by derry43** [InfotelGLPI/tasklists#47]
**Version of the plugin** : 
2.0.0-rc2 (data upgraded from 1.6.2 on GLPI 9.5.7)

**Version of your GLPI :** 
10.0.0 which was upgraded from 10.0 RC3 which was upgraded from 9.5.7

**Steps to reproduce** :

1. Copy tasklist 2.0.0-rc2 to plugins folder
2. Install (upgrade) tasklist plugin
3. Enable tasklist plugin
4. Browse to `Assistance -> Tasks lists`

**Expected result :**
Show kanban view as per tasklists 1.6.2 on GLPI 9.5.7

![tasklistson9 5 7](https://user-images.githubusercontent.com/47180698/164540408-c8d84a3f-96b0-451b-a141-60203adcbe1c.png)

**Actual result :**

Empty page

![tasklistsbug](https://user-images.githubusercontent.com/47180698/164540052-4a8cbe08-7ee1-42e5-a720-8e023550ee24.png)

**URL of the page :**

plugins/tasklists/front/kanban.php

* Screenshot of the problem (if pertinent) :

**Comment by derry43** [comment]
Issue remains on 2.0.0 release.

**Comment by cconard96** [comment]
Do you have any errors in the browser's console when you try to load the page (F12 key and then the Console tab)?

**Comment by derry43** [comment]
Following errors in Console when loading the page.

```
Uncaught TypeError: Cannot set properties of undefined (setting 'id')
    at appendColumn (Kanban.js:2046:23)
    at Object.<anonymous> (Kanban.js:2505:16)
    at l (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:25453)
    at Object.add [as done] (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:25786)
    at loadColumn (Kanban.js:2502:13)
    at Object.<anonymous> (Kanban.js:2756:19)
    at l (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:25453)
    at Object.fireWith [as resolveWith] (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:26272)
    at C (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:80410)
    at XMLHttpRequest.<anonymous> (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:82986)
appendColumn @ Kanban.js:2046
(anonymous) @ Kanban.js:2505
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
add @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
loadColumn @ Kanban.js:2502
(anonymous) @ Kanban.js:2756
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
C @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
load (async)
send @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ajax @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
eval @ VM13129:378
obj.<computed> @ VM13129:180
loadState @ Kanban.js:2729
init @ Kanban.js:2875
(anonymous) @ kanban.php:2262
u @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fire @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ready @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
U @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
2base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25 
        
       jQuery.Deferred exception: $(...).slider is not a function TypeError: $(...).slider is not a function
    at HTMLDocument.<anonymous> (https://glpi10.navsys.ad/plugins/tasklists/lib/kanban/js/Kanban.js:2244:37)
    at u (https://glpi10.navsys.ad/public/lib/base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:27491)
    at c (https://glpi10.navsys.ad/public/lib/base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:27819) undefined
E.Deferred.exceptionHook @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
add @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
eval @ VM13129:970
obj.<computed> @ VM13129:180
then @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
E.fn.ready @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
appendCard @ Kanban.js:2214
(anonymous) @ Kanban.js:2119
each @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:14
appendColumn @ Kanban.js:2117
(anonymous) @ Kanban.js:2505
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
add @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
loadColumn @ Kanban.js:2502
(anonymous) @ Kanban.js:2756
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
C @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
load (async)
send @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ajax @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
eval @ VM13129:378
obj.<computed> @ VM13129:180
loadState @ Kanban.js:2729
init @ Kanban.js:2875
(anonymous) @ kanban.php:2262
u @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fire @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ready @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
U @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
2base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25 
        
       Uncaught TypeError: $(...).slider is not a function
    at HTMLDocument.<anonymous> (Kanban.js:2244:37)
    at u (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:27491)
    at c (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:27819)
(anonymous) @ Kanban.js:2244
u @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
E.readyException @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
u @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fire @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
add @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
eval @ VM13129:970
obj.<computed> @ VM13129:180
then @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
E.fn.ready @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
appendCard @ Kanban.js:2214
(anonymous) @ Kanban.js:2119
each @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:14
appendColumn @ Kanban.js:2117
(anonymous) @ Kanban.js:2505
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
add @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
loadColumn @ Kanban.js:2502
(anonymous) @ Kanban.js:2756
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
C @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
load (async)
send @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ajax @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
eval @ VM13129:378
obj.<computed> @ VM13129:180
loadState @ Kanban.js:2729
init @ Kanban.js:2875
(anonymous) @ kanban.php:2262
u @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fire @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ready @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
U @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
```

**Comment by tsmr** [comment]
Sorry but Uncaught TypeError: $(...).slider is not a function
    at HTMLDocument.<anonymous> (Kanban.js:2244:37)

doesn't exist on last version. You have perhaps one version on marketplace folder & one into plugins folder ?

**Comment by derry43** [comment]
Re-installed and still seeing same issue, but console error is only ...

```
Uncaught TypeError: Cannot set properties of undefined (setting 'id')
    at appendColumn (Kanban.js:1978:26)
    at Object.<anonymous> (Kanban.js:2419:21)
    at l (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:25453)
    at Object.add [as done] (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:25786)
    at loadColumn (Kanban.js:2416:16)
    at Object.<anonymous> (Kanban.js:2671:29)
    at l (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:25453)
    at Object.fireWith [as resolveWith] (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:26272)
    at C (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:80410)
    at XMLHttpRequest.<anonymous> (base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25:82986)
appendColumn @ Kanban.js:1978
(anonymous) @ Kanban.js:2419
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
add @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
loadColumn @ Kanban.js:2416
(anonymous) @ Kanban.js:2671
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
C @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
load (async)
send @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ajax @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
eval @ VM449:378
obj.<computed> @ VM449:180
loadState @ Kanban.js:2643
init @ Kanban.js:2779
(anonymous) @ kanban.php:2236
u @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
c @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
setTimeout (async)
(anonymous) @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fire @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
l @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
fireWith @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
ready @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
U @ base.min.js?v=7866a42b7d36cd0ae8f31ff556d91bb8384127e7:25
```

**Comment by tsmr** [comment]
Can you try with last master version ? https://github.com/InfotelGLPI/tasklists/archive/refs/heads/master.zip

**Comment by derry43** [comment]
No change with master version. I can view the tasks by clicking on Search, where the tasks are all listed. It is the kanban view that is failing.

**Comment by Manel-vtlab** [comment]
Hi!

After migrate glpi v9.5.3 to v10.0.5 Tasklist plugin has been updated and activated succesfully (stay on marketplace folder only), **BUT the problem 'Blank page when open tasklists' still remains on glpi v10.0.5** with tasklist v2.0.3 exactly as @derry43 commented last april.

¿Someone working on it?

**Comment by Manel-vtlab** [comment]
Hi

The blank page appears only just after update GLPI, but in our case, adding the columns (button up-rigth) and mark the desired was the solution
![image](https://github.com/InfotelGLPI/tasklists/assets/119141245/687979eb-6a5f-4706-9c9d-e9e4fd07e703)

Now the kanban card view is ok.
